default_platform :ios

platform :ios do
  desc "Runs all the tests"
  lane :test do
  	scan(
	  workspace: "ContainerManager.xcworkspace",
	  scheme: "ContainerManager",
	  clean: true,
	  code_coverage: true,
	  skip_build: true
	)

	xcov(
	  workspace: "ContainerManager.xcworkspace",
	  scheme: "ContainerManager",
    minimum_coverage_percentage: 10.0
	)
  end
end
