default_platform :ios

platform :ios do
  desc "Runs all the tests"
  lane :test do

    clear_derived_data

  	scan(
	  workspace: "ContainerManager.xcworkspace",
	  scheme: "ContainerManager",
	  clean: true,
	  code_coverage: true,
	  skip_build: true
	)

	xcov(
	  workspace: "ContainerManager.xcworkspace",
	  scheme: "ContainerManager",
	)
  end
end
